### ISSUE TITLE
Consertar bug de integridade na tabela de log do bd

### ISSUE THREAD

**Issue by italovieira** [fases/susi#4]

**Comment by Mazuh** [comment]
Adicionando descrição: um delete from table executado na tabela de itens de cada campus poderia resultar na perda de logs (importante ferramenta de auditoria do sistema) porque a tabela de logs tem chave estrangeira referenciando a tabela de itens de campus.

**Comment by italovieira** [comment]
@YuriStyl3, espere eu implementar a correção que fecho a issue.

**Comment by yuriscosta-zz** [comment]
mi disculpe
