### ISSUE TITLE
Mudar cor de link

### ISSUE THREAD

**Issue by italovieira** [fases/susi#6]
Para que não fique ruim de enxergar como na imagem:
![2016-02-06-20 29 08](https://cloud.githubusercontent.com/assets/8337230/12870032/4f96fa14-cd10-11e5-8978-21489ba286d4.png)

**Comment by yuriscosta-zz** [comment]
Quando for chamar no cake, <a href="" class="link-item"></a>
coloca essa classe aí

**Comment by italovieira** [comment]
Qual classe?

**Comment by yuriscosta-zz** [comment]
oxe, eu comentei, mas n apareceu

**Comment by yuriscosta-zz** [comment]
a classe é "link-item"
