### ISSUE TITLE
Alertas de vencimento não estão na tela inicial

### ISSUE THREAD

**Issue by Mazuh** [fases/susi#9]
Substituir o conteúdo do arquivo da tela inicial ou quem sabe só redirecionar mesmo.

**Comment by Mazuh** [comment]
@italovieira estou certo ao supor que essa seja uma modificação simples e rápida de umas duas linhas? Se for mais trabalhoso eu ajudo.

**Comment by italovieira** [comment]
Como seriam os alertas?
A tela inicial exibe esses "alertas" assim.
![2016-02-21-01 12 20](https://cloud.githubusercontent.com/assets/8337230/13200847/4d5b1fc2-d838-11e5-85f1-5e59f2961f3f.png)

**Comment by Mazuh** [comment]
Sim. Mas quando fomos testar tava aparecendo uma tela em branco depois do login. O.o

**Comment by Mazuh** [comment]
Se já está funcionando pode fechar a issue! :D

**Comment by italovieira** [comment]
Só temos que dar um jeito nos redirecionamentos das páginas.

**Comment by italovieira** [comment]
Vou fechar, já que o problema se trata na verdade de outra issue.

**Comment by Mazuh** [comment]
@italovieira, reabri a issue pra investigarmos o que rolou no login de enfermeira, relatei no Trello.
